name: Build & Deploy

on:
  push:
    tags:
      - "*" # triggers only if push new tag version, like `0.8.4` or else

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      -
        name: Build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
          workdir: ./cmd/tarantulas
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Upload Assets to AWS S3 Bucket
        uses: shallwefootball/upload-s3-action@v1.1.3
        with:
          aws_key_id: ${{ secrets.AWS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws_bucket: ${{ secrets.AWS_BUCKET }}
          source_dir: './dist'
          destination_dir: ''

